version: '3'

services:
  tech-boost-php:
    container_name: tech-boost-php
    build: ./docker/php
    privileged: true
    expose: 
      - 9000
    volumes:
    - ./server/sample:/var/www
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - tech-boost-php-network

  tech-boost-web:
    image: nginx
    container_name: tech-boost-web
    ports:
    - 80:80
    volumes:
    - ./server/sample:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - tech-boost-php
    networks:
      - tech-boost-php-network

  tech-boost-db:
    image: mysql:5.7
    container_name: tech-boost-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    networks:
      - tech-boost-php-network


networks:
    tech-boost-php-network:
        external: true
